version: "3"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: ContainerMysql
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3007:80
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: ContainerPhpMyAdmin
        restart: always
        depends_on:
            - db
        ports:
            - 8085:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial
    www:
        build: docker
        container_name: ContainerFlorsen
        ports:
          - "9001:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/html
        restart: always
        networks:
            - tutorial
networks:
    tutorial:

volumes:
    db-data: