version: "3"

services:
  web:
    container_name: laravel_api
    build: .
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=gestion_des_jardinier
      - DB_USERNAME=root
      - DB_PASSWORD=root_password_here
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gestion_des_jardinier
      MYSQL_ROOT_PASSWORD: root_password_here
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8087:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root_password_here

volumes:
  db-data:
