version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=172.25.0.3
      - DB_PORT=3306
      - DB_DATABASE=gestion_des_jardinier
      - DB_USERNAME=root
      - DB_PASSWORD=root_password_here

  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: gestion_des_jardinier
      MYSQL_ROOT_PASSWORD: root_password_here
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    depends_on:
      - db
    environment:
      PMA_HOST: 172.25.0.3
      MYSQL_ROOT_PASSWORD: root_password_here

volumes:
  db-data:
