# Définit l'image de base en utilisant PHP 8.2 avec Apache
FROM php:8.2-apache

# Définit le répertoire de travail à /var/www/html
WORKDIR /var/www/html

# Copie de  tous les fichiers du répertoire courant vers le répertoire de travail
COPY . .

# Ajoute  de la configuration du serveur Apache pour définir le nom du serveur
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Met à jour et installe plusieurs packages nécessaires, y compris cron, vim, et diverses dépendances
RUN apt-get update \
    && apt-get install -qq -y --no-install-recommends \
    cron \
     vim \
     locales coreutils apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev;

# Configure les paramètres régionaux (locales) pour le support multilingue
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

# Télécharger et installer Composer (gestionnaire de dépendances PHP)
RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
   mv composer.phar /usr/local/bin/composer

# Configure et installe diverses extensions PHP nécessaires
RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql mysqli gd opcache intl zip calendar dom mbstring zip gd xsl && a2enmod rewrite
RUN pecl install apcu && docker-php-ext-enable apcu

# Ajoute l'outil d'installation d'extensions PHP et installe l'extension amqp
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions amqp
